name: mqc-redist
description: Downloads the MQ client library redist from IBM

inputs:
  client-version:
    description: MQ client version
    required: true

outputs:
  client-archive-path:
    description: MQ client archive path
    value: ${{ steps.download.outputs.client-archive-path }}
  client-install-path:
    description: MQ client installation path
    value: ${{ steps.install-path.outputs.client-install-path }}

runs:
  using: composite
  steps:
    - id: download
      name: Download MQC redist
      shell: bash
      run: |
        archive=$(./scripts/download-redist.sh ${{ inputs.client-version }} ${{ runner.os }} ${{ runner.temp }}/mqc_redist ) || exit $?
        echo client-archive-path=$archive >> $GITHUB_OUTPUT
    - id: install-macos
      if: ${{ runner.os == 'macOS' }}
      name: Install on macOS
      shell: bash
      run: |
        sudo installer -store -pkg ${{ steps.download.outputs.client-archive-path }} -target /
        echo /opt/mqm/bin >> $GITHUB_PATH
    - id: install-linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        mkdir -p $HOME/mqc
        tar -zxf ${{ steps.download.outputs.client-archive-path }} -C $HOME/mqc
        echo $HOME/mqc/bin >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$HOME/mqc/lib64" >> "$GITHUB_ENV"
    - id: install-windows
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        unzip -q -o ${{ steps.download.outputs.client-archive-path }} -d $HOME/mqc
    - id: install-windows-path
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        "$env:HOMEDRIVE$env:HOMEPATH\mqc\bin64" | Out-File -FilePath "$env:GITHUB_PATH" -Append
    - id: install-path
      shell: bash
      run: |
        case ${{ runner.os }} in
          Windows)
            echo client-install-path=$HOMEDRIVE$HOMEPATH >> $GITHUB_OUTPUT
            ;;
          Linux)
            echo client-install-path=$HOME/mqc >> $GITHUB_OUTPUT
            ;;
          macOS)
            echo client-install-path=/opt/mqm >> $GITHUB_OUTPUT
            ;;
        esac
