name: MQ client download
description: Download and install the MQ client library from IBM

inputs:
  download-path:
    description: Target download path for MQ client
    required: true
    default: ${{ runner.temp }}/mqc_download
  client-version:
    description: MQ client version
    required: true
  os:
    description: OS of MQ client
    required: true
    default: ${{ runner.os }}
  arch:
    description: Architecture of MQ client
    required: true
    default: ${{ runner.arch }}

outputs:
  client-archive-path:
    description: MQ client archive path
    value: ${{ steps.download.outputs.client-archive-path }}
  client-version:
    description: MQ client version downloaded
    value: ${{ steps.alias.client-version }}
  client-install-path:
    description: MQ client installation path
    value: ${{ steps.install-path.outputs.client-install-path }}

runs:
  using: composite
  steps:
    - id: alias
      name: MQ Version alias resolution
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        version=$(./scripts/version-alias.sh "${REQUESTED_VERSION}" "${REQUESTED_OS}${REQUESTED_ARCH}" )
        echo client-version="${version}" >> ${GITHUB_OUTPUT}
      env:
        REQUESTED_VERSION: ${{ inputs.client-version }}
        REQUESTED_OS: ${{ inputs.os }}
        REQUESTED_ARCH: ${{ inputs.arch }}
    - id: cache
      name: Cache MQ client library
      uses: actions/cache@v4
      with:
        path: ${{ inputs.download-path }}
        key: mqc-${{ inputs.os }}${{ inputs.arch }}-${{ steps.alias.outputs.client-version }}
    - id: download
      name: Download ${{ inputs.os }} ${{ inputs.arch }} MQ client library
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        archive=$(./scripts/download-client.sh "${MQ_CLIENT_VERSION}" "${REQUESTED_OS}${REQUESTED_ARCH}" "${MQ_DOWNLOAD_PATH}" ) || exit $?
        case ${{ runner.os }} in
          Windows) echo client-archive-path=$(cygpath -u "${archive}") >> ${GITHUB_OUTPUT};;
          *) echo client-archive-path="${archive}" >> ${GITHUB_OUTPUT};;
        esac
      env:
        MQ_CLIENT_VERSION: ${{ steps.alias.outputs.client-version }}
        MQ_DOWNLOAD_PATH: ${{ inputs.download-path }}
        REQUESTED_OS: ${{ inputs.os }}
        REQUESTED_ARCH: ${{ inputs.arch }}
    - id: extract-macos
      name: Extract macOS MQ client
      if: ${{ inputs.os == 'macOS' }}
      shell: bash
      run: sudo installer -store -pkg "${MQ_CLIENT_ARCHIVE_PATH}" -target /
      env:
        MQ_CLIENT_ARCHIVE_PATH: ${{ steps.download.outputs.client-archive-path }}
    - id: install-macos
      name: Install MQ client library on macOS
      if: ${{ inputs.os == 'macOS' && runner.os == 'macOS' }}
      shell: bash
      run: echo /opt/mqm/bin >> ${GITHUB_PATH}

    - id: extract-linux
      name: Extract Linux MQ client library
      if: ${{ inputs.os == 'Linux' }}
      shell: bash
      run: |
        mkdir -p "${HOME}/mqc"
        tar -zxf ${MQ_CLIENT_ARCHIVE_PATH} -C "${HOME}/mqc"
      env:
        MQ_CLIENT_ARCHIVE_PATH: ${{ steps.download.outputs.client-archive-path }}
    - id: install-linux
      name: Install MQ client library on Linux
      if: ${{ inputs.os == 'Linux' && runner.os == 'Linux' && inputs.arch == runner.arch }}
      shell: bash
      run: |
        echo $HOME/mqc/bin >> ${GITHUB_PATH}
        echo "LD_LIBRARY_PATH=${HOME}/mqc/lib64" >> "${GITHUB_ENV}"

    - id: extract-windows
      name: Extract Windows MQ client library
      if: ${{ inputs.os == 'Windows' }}
      shell: bash
      run: 7z x "${MQ_CLIENT_ARCHIVE_PATH}" -o"${HOME}/mqc"
      env:
        MQ_CLIENT_ARCHIVE_PATH: ${{ steps.download.outputs.client-archive-path }}
    - id: install-windows
      name: Install MQ client library on Windows
      if: ${{ runner.os == 'Windows' && runner.os == 'Windows' && inputs.arch == runner.arch }}
      shell: pwsh
      run: |
        "$env:HOMEDRIVE$env:HOMEPATH\mqc\bin64" | Out-File -FilePath "$env:GITHUB_PATH" -Append

    - id: install-path
      name: Set the client-install-path
      shell: bash
      run: |
        case ${REQUESTED_OS} in
          Linux|Windows) client_install_path="${HOME}/mqc" ;;
          macOS) client_install_path=/opt/mqm ;;
        esac

        case ${{ runner.os }} in
          Windows) echo client-install-path=$(cygpath -w "${client_install_path}") >> ${GITHUB_OUTPUT} ;;
          *) echo client-install-path="${client_install_path}" >> ${GITHUB_OUTPUT} ;;
        esac
      env:
        REQUESTED_OS: ${{ inputs.os }}
