name: mqc-redist
description: Downloads the MQ client library redist from IBM

inputs:
  download-path:
    description: Path to download the MQ client library
    default: ${{ runner.temp }}/mqc_redist
    required: true
  client-version:
    description: MQ client version
    required: true

outputs:
  client-archive-path:
    description: MQ client archive path
    value: ${{ steps.download.outputs.client-archive-path }}
  client-install-path:
    description: MQ client installation path
    value: ${{ steps.install-path.outputs.client-install-path }}

runs:
  using: composite
  steps:
    - id: download
      name: Download MQC redist
      shell: bash
      run: |
        archive=$(./scripts/download-redist.sh ${{ inputs.client-version }} ${{ runner.os }} ${{ inputs.download-path }}) || exit $?
        echo client-archive-path=$archive >> $GITHUB_OUTPUT
    - id: install-macos
      if: ${{ runner.os == 'macOS' }}
      name: Install on macOS
      shell: bash
      run: |
        sudo installer -store -pkg ${{ steps.download.outputs.client-archive-path }} -target /
    - id: install-linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        mkdir -p ${{ runner.temp }}/mqc
        tar -zxf ${{ steps.download.outputs.client-archive-path }} -C ${{ runner.temp }}/mqc
    - id: install-windows
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: |
        unzip -q -o ${{ steps.download.outputs.client-archive-path }} -d /tmp/mqc
    - id: install-path
      shell: bash
      run: |
        case ${{ runner.os }} in
          Windows)
            echo client-install-path=/tmp/mqc >> $GITHUB_OUTPUT
            ;;
          Linux)
            echo client-install-path=${{ runner.temp }}/mqc >> $GITHUB_OUTPUT
            ;;
          macOS)
            echo client-install-path=/opt/mqm >> $GITHUB_OUTPUT
            ;;
        esac
