name: mqc-redist
description: Download and install the MQ client library from IBM

inputs:
  download-path:
    description: Target download path for MQ client
    required: true
    default: ${{ runner.temp }}/mqc_download
  client-version:
    description: MQ client version
    required: true

outputs:
  client-archive-path:
    description: MQ client archive path
    value: ${{ steps.download.outputs.client-archive-path }}
  client-install-path:
    description: MQ client installation path
    value: ${{ steps.install-path.outputs.client-install-path }}

runs:
  using: composite
  steps:
    - id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.download-path }}
        key: mqc-${{ runner.os }}-${{ inputs.client-version }}
    - id: download
      name: Download MQC client
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        archive=$(./scripts/download-redist.sh "${MQ_CLIENT_VERSION}" ${{ runner.os }} "${MQ_DOWNLOAD_PATH}" ) || exit $?
        echo client-archive-path="${archive}" >> ${GITHUB_OUTPUT}
      env:
        MQ_CLIENT_VERSION: ${{ inputs.client-version }}
        MQ_DOWNLOAD_PATH: ${{ inputs.download-path }}
    - id: install-macos
      if: ${{ runner.os == 'macOS' }}
      name: Install on macOS
      shell: bash
      run: |
        sudo installer -store -pkg ${{ steps.download.outputs.client-archive-path }} -target /
        echo /opt/mqm/bin >> ${GITHUB_PATH}
    - id: install-linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        mkdir -p "${HOME}/mqc"
        tar -zxf ${{ steps.download.outputs.client-archive-path }} -C "${HOME}/mqc"
        echo $HOME/mqc/bin >> ${GITHUB_PATH}
        echo "LD_LIBRARY_PATH=${HOME}/mqc/lib64" >> "${GITHUB_ENV}"
    - id: install-windows
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        7z x ${{ steps.download.outputs.client-archive-path }} -o"$env:HOMEDRIVE$env:HOMEPATH\mqc"
        "$Env:HOMEDRIVE$Env:HOMEPATH\mqc\bin64" | Out-File -FilePath "$env:GITHUB_PATH" -Append
    - id: install-path
      shell: bash
      run: |
        case ${{ runner.os }} in
          Windows)
            echo client-install-path=$HOMEDRIVE$HOMEPATH\\mqc >> ${GITHUB_OUTPUT}
            ;;
          Linux)
            echo client-install-path="${HOME}/mqc" >> ${GITHUB_OUTPUT}
            ;;
          macOS)
            echo client-install-path=/opt/mqm >> ${GITHUB_OUTPUT}
            ;;
        esac
