name: mqc-redist
description: Downloads the MQ client library redist from IBM

inputs:
  download-path:
    description: Path to download the MQ client library
    default: /tmp/mqc_redist
    required: true
  client-version:
    description: MQ client version
    required: true

outputs:
  client-archive-path:
    description: MQ client archive path
    value: ${{ steps.download.outputs.client-archive-path }}

runs:
  using: composite
  steps:
    - id: download
      name: Download MQC redist
      shell: bash
      run: |
        archive=$(./scripts/download-redist.sh ${{ inputs.client-version }} ${{ runner.os }} ${{ inputs.download-path }}) || exit $?
        echo client-archive-path=$archive >> $GITHUB_OUTPUT
    - id: install-macos
      if: ${{ runner.os == 'macOS' }}
      name: Install on macOS
      shell: bash
      run: sudo installer -store -pkg ${{ steps.download.outputs.client-archive-path }} -target /
    - id: extract-linux
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        mkdir -p /tmp/mqc_install
        tar -zxf ${{ steps.download.outputs.client-archive-path }} -C /tmp/mqc_install
    - id: extract-windows
      if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: unzip -q -o ${{ steps.download.outputs.client-archive-path }} -d /tmp/mqc_install
