name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
          - ubuntu-24.04-arm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./
        id: download
        with:
          client-version: latest
      - run: dspmqver
  cross:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        client:
          - os: Windows
            arch: X86
          - os: Linux
            arch: X86
          - os: Linux
            arch: s390x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./
        id: download
        with:
          client-version: latest
          os: ${{ matrix.client.os }}
          arch: ${{ matric.client.arch }}
