on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./
        id: download
        with:
          client-version: 9.4.1.1
      - env:
          MQ_HOME: ${{ steps.download.outputs.client-install-path }}
        run: dspmqver
