on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          download-path: /tmp/mqc
          mq-client-version: 9.4.0.5
