on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          download-path: /tmp/mqc
          client-version: 9.4.0.5
