name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  download:
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: windows-latest
            mq-version: 9.4.1.1
          - os: ubuntu-24.04
            mq-version: 9.4.1.1
          - os: macos-latest
            mq-version: 9.4.1.0
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./
        id: download
        with:
          client-version: ${{ matrix.build.mq-version }}
      - env:
          MQ_HOME: ${{ steps.download.outputs.client-install-path }}
        run: dspmqver
