on:
  workflow_dispatch:
  schedule: [cron: "40 4 * * *" ]

permissions:
  pull-requests: write
  contents: write

jobs:
  new_redist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: qoomon/actions--setup-git@v1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
      - run: pip install -r requirements.txt
      - run: python new-redist.py checksums.txt
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PULL_BRANCH=redist_${{github.run_id}}_${{github.run_number}}
          git diff --stat --exit-code || {
            git switch -C $PULL_BRANCH
            git commit -am 'redist: New MQC redist' || true
            git push origin --set-upstream $PULL_BRANCH
            gh pr create --title 'New MQC redist' --body 'Created by Github Action' --base ${{github.ref}} || true
          }
