name: MQ Client Sync

on:
  workflow_dispatch:
  schedule: [cron: "40 4 * * *" ]

permissions: {}

jobs:
  sync_client:
    timeout-minutes: 60
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
          ref: client_sync
      - uses: qoomon/actions--setup-git@8e6bd30ac05e17a81b61169daae62cb6b7e61294 #v1.1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
      - run: pip install -r requirements.txt
      - run: python sync-client.py checksums.txt
      - name: Create pull request
        if: always()
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff --stat --exit-code || {
            git commit -am 'client: Sync MQ client list'
            git push
            gh pr view --json number >/dev/null 2>&1 || gh pr create --base main --title "Client Sync ${{ github.run_id }}" --body "Synchronise with latest MQ libraries"
          }
